# Generated by Django 5.2 on 2025-04-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_sent_at_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
