# Generated by Django 5.2 on 2025-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contactmessage_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_demo',
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
