# Generated by Django 5.2 on 2025-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_project_live_demo_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='defaults/placeholder.jpg', null=True, upload_to='projects/'),
        ),
    ]
