# Generated by Django 5.2 on 2025-05-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_projectimage_image_projectimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
