# Generated by Django 5.2 on 2025-05-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_projectimage_image_url_projectimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
